services:

  jenkins:
    image: jenkins/jenkins:2.479.1
    container_name: jenkins
    ports:
      - 8082:8082
      - 50000:50000
    environment:
      - JENKINS_OPTS=--httpPort=8082
    volumes:
      - jenkins_home:/var/jenkins_home

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.0
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KC_HOSTNAME=keycloak
      - KC_HTTP_PORT=8080
      - KC_HTTP_ADMIN_PORT=8081
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=P4ssw0rd
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: keycloak-db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=P4ssw0rd
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    name: keycloak-db-data
  jenkins_home:
    name: jenkins-home

networks:
  default:
    name: appdev
    driver: bridge
